name: go-pmtiles

on: [push]

jobs:
  master_push_to_registry:
    name: Push Docker image to GitHub Packages as with Tag 'latest'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          context: ./
          dockerfile: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: protomaps/go-pmtiles/go-pmtiles
          tags: master
